# Iris Flower

##### Goals
- Import dataset
- Train a classifier
- Predict label for new flower
- Visualize the tree

## Importando dataset


In [24]:
from sklearn.datasets import load_iris
import numpy as np

In [2]:
iris = load_iris()

In [3]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='<U10')

In [11]:
iris.data[0:10]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1]])

In [23]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='<U10')

### Separando conjunto para testes

In [25]:
teste_idx = [0, 50, 100]

# training data
train_target = np.delete(iris.target, teste_idx)
train_data = np.delete(iris.data, teste_idx, axis = 0)

# teste data
test_target = iris.target[teste_idx]
test_data = iris.data[teste_idx]

### Criando e Treinando classificador

In [26]:
from sklearn import tree

In [27]:
clf = tree.DecisionTreeClassifier()

In [28]:
clf.fit(train_data, train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

### Testando prediçoes

In [33]:
test_target

array([0, 1, 2])

In [34]:
clf.predict(test_data)

array([0, 1, 2])

### Vizualizando dados

In [36]:
from sklearn.externals.six import StringIO

In [39]:
dot_data = StringIO()

In [52]:
tree.export_graphviz(clf, out_file=dot_data, feature_names=iris.feature_names, class_names=iris.target_names, filled=True, rounded=True, impurity=False)

PROLEMA COM LIB PYDOTPLUS

In [57]:
import pydotplus
tree.export_graphviz(clf, out_file=dot_data)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf("iris.pdf")

ModuleNotFoundError: No module named 'pydotplus'