In [1]:
%matplotlib inline
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
import metrics as mt
import stats as sts

# Machine Learning Library 

In [2]:
X = np.array([[1], [2], [4], [3], [5]])
y = np.array([1, 3, 3, 2, 5])

In [3]:
sts.mean(X)

3.0

In [4]:
sts.var(X)

2.0

In [5]:
np.var(X)

2.0

In [6]:
sts.stdev(X)

1.4142135623730951

In [7]:
np.std(X)

1.4142135623730951

In [8]:
mt.mae(X, y)

7.7999999999999998

In [9]:
import linear_regression as lrg

In [10]:
import linear_model as lmodel

In [11]:
lrg.gradient_descendent(X, y)

learning_rate=0.0001, number_iterations=10000
Após 10000 iterações, obtemos b0 = 2.3204581107661904, b1 = 0.1328254138388434, error = 9.00928410181371


(2.3204581107661904, 0.13282541383884339)

In [12]:
lmodel.lr.gradient_descendent(X, y, learning_rate=0.000001,num_iterations=100000)

learning_rate=1e-06, number_iterations=100000
Após 100000 iterações, obtemos b0 = 0.6039674669314011, b1 = 0.6082601593017786, error = 13.188944656252982


(0.60396746693140113, 0.60826015930177857)

In [13]:
slr = lmodel.SimpleLinearRegression()

In [14]:
slr.fit(X, y)

learning_rate=0.0001, number_iterations=100000
Após 100000 iterações, obtemos b0 = 2.7999998817588554, b1 = 3.275090105622739e-08, error = 8.800000000000013


In [15]:
slr.predict(X)

array([[ 2.79999991],
       [ 2.79999995],
       [ 2.80000001],
       [ 2.79999998],
       [ 2.80000005]])

In [16]:
from sklearn import linear_model

In [17]:
model = linear_model.LinearRegression()

In [18]:
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [19]:
model.predict(X)

array([ 1.2,  2. ,  3.6,  2.8,  4.4])

In [20]:
model.coef_, model.intercept_

(array([ 0.8]), 0.39999999999999991)