# Lista 3 - Criação de uma biblioteca

In [1]:
import numpy as np
# Library
import stats as sts
import metrics as mts
import linear_model as lm
import resample as rs
# SKLEARN
from sklearn import linear_model as lmodel
from sklearn import metrics

## Representação dos dados

In [2]:
X = np.array([[1400],[1600],[1700],[1875],[1100],[1550],[2350],[2450],[1425],[1700]])
y = np.array([245000, 312000, 279000, 308000,199000,219000, 405000,324000,319000,255000])

## Estatisticas dos dados

### Media

In [3]:
sts.mean(X)

1715.0

### Desvio padrao

In [4]:
sts.stdev(X)

396.42149285829595

### Variancia

In [5]:
sts.var(X)

157150.0

## Divisao do dados de treino e de teste


In [6]:
tam = len(X)
idx_train, idx_test = rs.split_train_test(tam, 0.7)

In [7]:
X_train = X[idx_train] # onde idx_train é um array com os índices dos dados de treino.
y_train = y[idx_train]
X_test = X[idx_test]
y_test = y[idx_test]

In [8]:
X_train[:,0], y_train, idx_train

(array([1700, 1425, 1100, 1700, 1600, 2350, 2450]),
 array([279000, 319000, 199000, 255000, 312000, 405000, 324000]),
 [2, 8, 4, 9, 1, 6, 7])

## Criação dos modelos de predição

In [9]:
model = lm.SimpleLinearRegression()
sk_model = lmodel.LinearRegression()

## Treino dos modelos

In [10]:
model.fit(X_train, y_train)
sk_model.fit(X_train, y_train)

b0=122467.52256260332, b1=100.26185331130034


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
sk_model.intercept_, sk_model.coef_[0]

(122467.52256260326, 100.26185331130037)

## Prediçoes

In [12]:
y_pred = model.predict(X_test)
y_pred

b0=122467.52256260332, b1=100.26185331130034


array([ 310458.49752129,  262834.11719842,  277873.39519512])

In [13]:
y_sk_pred = sk_model.predict(X_test)
y_sk_pred

array([ 310458.49752129,  262834.11719842,  277873.39519512])

## Calculo do erros

### MSE

In [14]:
mts.mse(y=y_test, y_pred=y_pred)

1263392202.7033188

In [15]:
mts.mse(y_test, y_sk_pred)

1263392202.7033181

### RMSE

In [16]:
mts.rmse(y_test, y_pred)

35544.228824146951

In [17]:
mts.rmse(y_test, y_sk_pred)

35544.228824146936

### MAE

In [18]:
mts.mae(y_test, y_pred)

26388.669971611391

In [19]:
mts.mae(y_test, y_sk_pred)

26388.669971611369